1)SELECT count(*) as "an" FROM studenti GROUP BY an;
2)SELECT count(*),grupa,an from studenti GROUP BY an,grupa ORDER BY an,grupa;
3)SELECT count(*),grupa,an from studenti WHERE bursa IS NOT NULL GROUP BY an,grupa ORDER BY an,grupa;
3') SELECT count(*),grupa,an,count(bursa) FROM studenti GROUP BY an,grupa ORDER BY an,grupa;
4)SELECT sum(bursa) FROM studenti;
5)SELECT avg(nvl(bursa,0)) FROM studenti;
5') SELECT sum(bursa)/count(*) FROM studenti;
6) SELECT valoare,count(valoare) FROM note GROUP BY valoare ORDER BY valoare DESC;
6')SELECT valoare,count(*) FROM note GROUP BY valoare ORDER BY valoare DESC;
7)SELECT count(*),to_char(data_notare,'DAY') FROM note GROUP BY to_char(data_notare,'DAY') ORDER BY count(*) DESC;
8)SELECT count(*),to_char(data_notare,'DAY') FROM note GROUP BY to_char(data_notare,'DAY'),to_char(data_notare,'D') ORDER BY to_char(data_notare,'DAY');
9)SELECT nume,prenume,avg(valoare) FROM studenti natural join note GROUP BY nr_matricol,nume,prenume ORDER by avg(valoare) DESC;
10) SELECT nume,prenume,avg(valoare) FROM studenti  LEFT JOIN note n on studenti.nr_matricol=n.nr_matricol GROUP BY n.nr_matricol,nume,prenume ORDER by avg(valoare) DESC;
11) SELECT nume,prenume,avg(NVL(valoare,0)) FROM studenti  LEFT JOIN note n on studenti.nr_matricol=n.nr_matricol GROUP BY n.nr_matricol,nume,prenume ORDER by avg(valoare) DESC;
12) SELECT nume,prenume,avg(NVL(valoare,0)) FROM studenti  LEFT JOIN note n on studenti.nr_matricol=n.nr_matricol GROUP BY n.nr_matricol,nume,prenume having avg(valoare)>8 ORDER by avg(valoare) DESC;
13)SELECT nume,prenume,min(valoare),max(valoare),avg(valoare) FROM studenti  LEFT JOIN note n on studenti.nr_matricol=n.nr_matricol GROUP BY n.nr_matricol,nume,prenume having min(valoare)>=7 ORDER by avg(valoare) DESC;
14)SELECT nume,prenume,avg(valoare) FROM studenti left join note n on studenti.nr_matricol=n.nr_matricol GROUP BY n.nr_matricol,nume,prenume having count(*)>=4;
15)SELECT nume,prenume,avg(valoare),grupa FROM studenti left join note n on studenti.nr_matricol=n.nr_matricol where grupa='A2' AND an=3 GROUP BY n.nr_matricol,nume,prenume,grupa;
15') SELECT nume,prenume,avg(valoare),grupa FROM studenti left join note n on studenti.nr_matricol=n.nr_matricol GROUP BY n.nr_matricol,nume,prenume,grupa,an HAVING grupa='A2' and an=3;
16)SELECT max(avg(valoare)) FROM note GROUP BY nr_matricol; 
17)SELECT titlu_curs,max(n.valoare),min(n.valoare) FROM cursuri LEFT JOIN note n ON cursuri.id_curs=n.id_curs GROUP BY titlu_curs;
 SELECT titlu_curs,max(valoare),min(valoare) FROM cursuri natural JOIN note GROUP BY titlu_curs;
18+)SELECT titlu_curs,count(distinct valoare),min(valoare),max(valoarE) FROM cursuri natural JOIN note GROUP BY titlu_curs;
